---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: pup-os
description: A furry Linux distro!

base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    remove:
      # Remove Firefox in favor of the flatpak.
      - firefox
      - firefox-langpacks

  - type: default-flatpaks
    notify: true
    system:
      install:
        - org.mozilla.firefox
    user: {}

  - type: signing
