---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: pup-os
description: A furry Linux distro!

base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: os-release
    source: local
    name: "PupOS"
    id: "pup-os"
    id_like:
      - "fedora"
    extra:
      LOGO: "fedora-logo-icon"
      HOME_URL: "https://github.com/justlark/pup-os"

  - type: rpm-ostree
    remove:
      # Remove Firefox in favor of the flatpak.
      - firefox
      - firefox-langpacks

  - type: default-flatpaks
    notify: true
    system:
      install:
        - org.mozilla.firefox
    user: {}

  - type: gnome-backgrounds
    source: local
    backgrounds:
      - name: "Eepy Fox"
        path: "/usr/share/backgrounds/pup-os/eepy-fox.jpg"
      - name: "Ocean Husky"
        path: "/usr/share/backgrounds/pup-os/ocean-husky.jpg"
      - name: "Smiling Husky"
        path: "/usr/share/backgrounds/pup-os/smiling-husky.jpg"

  - type: gschema-overrides
    include:
      - zz1-pup-os.gschema.override

  - type: signing
